### ISSUE TITLE
support for direct compilation options in cere build command 

### ISSUE THREAD

**Issue by lavanyar2000** [benchmark-subsetting/cere#3]
Currently the cere build command expects "make" as the build command. Request for support of directly giving the compilation options in the build-cmd of cere.

**Comment by pablooliveira** [comment]
Thanks @lavanyar2000 ! 

Supporting this is a good idea. We should:
- add a build clean command to cere configure so we can get rid of the Makefile specific "-B" option
- change the way ccc retrieves CERE_MODE. Instead of explicitely setting it after the build cmd, it should be passed as an environment variable.

@Chadi-akel, as discussed I'm assigning this to you.

**Comment by Chadi-akel** [comment]
Fixed in #26
