### ISSUE TITLE
Using cere profile on test_Omp1 results in an empty call graph file

### ISSUE THREAD

**Issue by pablooliveira** [benchmark-subsetting/cere#46]
To reproduce:

```
$ cd tests/test_Omp_01/
$ ../../cere configure --build-cmd=make --run-cmd=./test --clean-cmd="make clean"
$ cat .cere/profile/graph_.dot 
strict digraph  {
}
```

**Comment by Chadi-akel** [comment]
The execution time of this test is so short that the google CPU profiler does not even measure one sample. So the call graph is empty.
Since the goal of this test is to be sure that the environment is configured to run PCERE, we should let it like that, and add new tests for others feature like profiling.

**Comment by pablooliveira** [comment]
Ok thanks !
