### ISSUE TITLE
test 10 potential error if compiled with -O2

### ISSUE THREAD

**Issue by mihailpopov** [benchmark-subsetting/cere#51]
Test 10 source code is composed of:
- a global initialized static int variable
- a loop which prints this variable value

CERE extracts the loop as a codelet.

Test 10 ensures that the codelet and the original loop both print the same value.

The test is compiled with -O0 and is successful.
However, compiling both the original code and the codelet with -O2 makes it fail: 
the codelet print a wrong value for the variable.

```
-O0
original value = 42
codelet value = 42


-O2
original value = 42
codelet value = 1
```

**Comment by pablooliveira** [comment]
I've looked into this. In O3, because value is declared as "static" llvm can prove that the only two admissible values are 10 and 42. Therefore instead of storing the real value, it stores a flag 0 or 1 that tells which one of the two states is currently set.

```
  %.b = load i1* @value, align 1
  %1 = select i1 %.b, i32 42, i32 10
  %2 = tail call i32 (i8*, ...)* @printf(i8* getelementptr inbounds ([12 x i8]* @.str, i64 0, i64 0), i32 %1) #2
```

This optimization is done during dump, but is not done during replay because we "globalize" internal values. This was needed in 6762778 to be able to relocate static objects at replay.

I think the correct fix here is to also "globalize" during dump...

**Comment by pablooliveira** [comment]
After trying the different linkage types of LLVM (http://llvm.org/docs/LangRef.html#linkage-types), it seems there is no intermediate linkage that would both allow to preserve the optimization and to allow replacing the symbols correctly during replay. 

Therefore we must also "globalize" during dump.
